### ISSUE TITLE
v5.0.0 beta 4 - Avatar legs wont easily bent unless its touching the ground

### ISSUE THREAD

**Issue by orangpelupa** [nicoco007/BeatSaberCustomAvatars#5]
name: Bug report
about: FBT Avatar legs
title: ''Avatar legs wont easily bent unless its touching the ground"
labels: bug

Tracker:
- Kinect via Driver4VR
- Kinect via KinectToVR by sharky20

Avatar:
- avatars made by SeventyTwo on Modelsaber

both gives legs that are very hard to bend unless its touching the ground/floor. Thus when I move my knee up, the avatar leg wont move the knee up.

but if i crouch, the legs will bend properly.

Used to be working fine with custom avatar on beat saber 1.5. Tested on VR chat, the legs are fine. So its not the issue of kinect/driver4vr/kinecttovr i think

**Comment by orangpelupa** [comment]
using BETA3 i can bend my legs, albeit still doesnt feel as 1:1 as the one on Beatsaber 1.5.0

**Comment by nicoco007** [comment]
A lot of stuff related to tracking has changed so I might have broken something somewhere. Kinect-based tracking isn't quite supported yet since I haven't had time to take a real look at it yet but I'm working on it.

**Comment by nicoco007** [comment]
I believe this has been fixed in beta 6. Could you let me know if it is?

**Comment by rizputin** [comment]
Having same issue (using Monika avatar by SeventyTwo). Feet are slightly above ground, making knee bending difficult unless over-extending. Tried tweaking the room Y axis, but made no difference. Any thoughts on manually adjusting the calibration?

**Comment by Tonic0** [comment]
Still broken for me in Beta 6 on majority of avatars downloaded from the web. Only avatar that has feet touching ground somewhat properly is the full body tracking template model. I'm using Index with 3x Vive Tracker pucks placed on both feet + waist.

Calibration only seems to twist my feet trackers to an unnatural position, when I set them manually on my feet to match the avatar in the game and clear the calibration, I get the most natural and accurate body position.

Old custom avatars used to work nearly perfect in 1.5.0 and older BS versions, as long as I set the room floor offset to -0.5, but now room floor offsets don't help and all my avatars seem to be floating half a meter in the air unless I crouch really hard. The "floor height adjust" option also doesn't seem to do anything, does it rely on some extensions other than BSML and DOVR?

Thanks for your work on the plugin! Having custom avatars for screen recording makes BS so much more fun.
